# Generated by Django 5.2.1 on 2025-05-26 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(db_index=True, max_length=10, verbose_name='Vocabulario en chino')),
                ('pinyin', models.CharField(max_length=10)),
                ('traduccion', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('S', 'Sustantivo'), ('V', 'Verbo'), ('A', 'Adjetivo'), ('AD', 'Adverbio'), ('P', 'Pronombre'), ('C', 'Conjunción'), ('I', 'Interjección'), ('D', 'Determinante'), ('N', 'Numeral'), ('O', 'Otro')], db_index=True, max_length=2)),
                ('nivel_hsk', models.SmallIntegerField(db_index=True, default=1)),
                ('ejemplo', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nivel_hsk', 'tipo', 'palabra'],
                'unique_together': {('palabra', 'usuario')},
            },
        ),
    ]
