# Generated by Django 5.2.1 on 2025-05-30 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulario', '0002_palabra_delete_vocabulario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='palabra',
            unique_together={('palabra', 'pinyin', 'tipo', 'nivel_hsk', 'usuario')},
        ),
        migrations.AlterField(
            model_name='palabra',
            name='traduccion',
            field=models.CharField(max_length=200),
        ),
    ]
